import { describe, expect, it } from 'vitest';
import type { AgentMessage } from '../types.js';
import { deriveClaims, renderStatusMarkdown } from './status.js';

const entries: AgentMessage[] = [
  { ts: '2026-07-17T10:00:00.000Z', agent: 'claude:s1', repo: '/repo', event: 'status', status: 'working', task: 'FE-5' },
  { ts: '2026-07-17T10:01:00.000Z', agent: 'claude:s1', repo: '/repo', event: 'claim', files: ['src/a.ts'], task: 'FE-5' },
  { ts: '2026-07-17T10:02:00.000Z', agent: 'codex:s2', repo: '/repo', event: 'blocked', blockers: ['API schema'], message: 'waiting' },
  { ts: '2026-07-17T10:03:00.000Z', agent: 'claude:s1', repo: '/repo', event: 'message', message: 'halfway' },
];

describe('STATUS.md', () => {
  it('derives active claims and removes them on release/done', () => {
    expect(deriveClaims(entries)).toHaveLength(1);
    expect(deriveClaims([...entries, { ts: '2026-07-17T10:04:00.000Z', agent: 'claude:s1', repo: '/repo', event: 'release', files: ['src/a.ts'] }])).toEqual([]);
  });

  it('renders generated status, claims, blockers, and recent messages', () => {
    expect(renderStatusMarkdown('/repo', entries)).toMatchInlineSnapshot(`
      "<!-- GENERATED BY AGENTDECK — DO NOT EDIT -->
      # Agent Status

      ## Current
      | Agent | Task | Status | Updated |
      |---|---|---|---|
      | claude:s1 | FE-5 | working | 2026-07-17T10:00:00.000Z |

      ## Active Claims
      | File | Agent | Task | Since |
      |---|---|---|---|
      | src/a.ts | claude:s1 | FE-5 | 2026-07-17T10:01:00.000Z |

      ## Blockers
      | Agent | Blockers | Message |
      |---|---|---|
      | codex:s2 | API schema | waiting |

      ## Recent Messages
      | Time | Agent | Event | Message |
      |---|---|---|---|
      | 2026-07-17T10:03:00.000Z | claude:s1 | message | halfway |
      | 2026-07-17T10:02:00.000Z | codex:s2 | blocked | waiting |
      "
    `);
  });
});
