import type { AgentMessage, FileClaim } from '../types.js';

const clean = (value: string | undefined): string => (value ?? '—').replaceAll('|', '\\|').replaceAll('\n', ' ');

export function deriveClaims(entries: AgentMessage[]): FileClaim[] {
  const claims = new Map<string, FileClaim>();
  for (const entry of entries) {
    if (entry.event === 'done') {
      for (const [key, claim] of claims) if (claim.agent === entry.agent) claims.delete(key);
      continue;
    }
    for (const file of entry.files ?? []) {
      const key = `${entry.repo}\0${file}\0${entry.agent}`;
      if (entry.event === 'claim') {
        const claim: FileClaim = { repo: entry.repo, file, agent: entry.agent, since: entry.ts };
        if (entry.task) claim.task = entry.task;
        claims.set(key, claim);
      } else if (entry.event === 'release') claims.delete(key);
    }
  }
  return [...claims.values()];
}

export function renderStatusMarkdown(repoPath: string, entries: AgentMessage[]): string {
  const current = new Map<string, AgentMessage>();
  for (const entry of entries) if (entry.status) current.set(entry.agent, entry);
  const claims = deriveClaims(entries);
  const blockers = entries.filter((entry) => entry.event === 'blocked').slice(-10);
  const messages = entries.filter((entry) => entry.message).slice(-10).reverse();
  const lines = [
    '<!-- GENERATED BY AGENTDECK — DO NOT EDIT -->', '# Agent Status', '',
    '## Current', '| Agent | Task | Status | Updated |', '|---|---|---|---|',
    ...[...current.values()].map((entry) => `| ${clean(entry.agent)} | ${clean(entry.task)} | ${clean(entry.status)} | ${entry.ts} |`),
    '', '## Active Claims', '| File | Agent | Task | Since |', '|---|---|---|---|',
    ...claims.map((claim) => `| ${clean(claim.file)} | ${clean(claim.agent)} | ${clean(claim.task)} | ${claim.since} |`),
    '', '## Blockers', '| Agent | Blockers | Message |', '|---|---|---|',
    ...blockers.map((entry) => `| ${clean(entry.agent)} | ${clean(entry.blockers?.join(', '))} | ${clean(entry.message)} |`),
    '', '## Recent Messages', '| Time | Agent | Event | Message |', '|---|---|---|---|',
    ...messages.map((entry) => `| ${entry.ts} | ${clean(entry.agent)} | ${entry.event} | ${clean(entry.message)} |`),
    '',
  ];
  void repoPath;
  return lines.join('\n');
}
